version: '2.1'
services:
  node0:
    image: matrixkv
    ports:
      - "8080:8080"
    volumes:
      - ./cfg/node0.toml:/etc/cube.toml
      - /data/matrixkv/node0:/data/matrixkv
    command: 
      - --addr=node0:8080
      - --cfg=/etc/cube.toml
      # shard will split after 16 bytes
      - --shard-capacity=16

  node1:
    image: matrixkv
    ports:
      - "8081:8080"
    volumes:
      - ./cfg/node1.toml:/etc/cube.toml
      - /data/matrixkv/node1:/data/matrixkv
    command: 
      - --addr=node1:8080
      - --cfg=/etc/cube.toml
      # shard will split after 16 bytes
      - --shard-capacity=16
    depends_on:
      - node0

  node2:
    image: matrixkv
    ports:
      - "8082:8080"
    volumes:
      - ./cfg/node2.toml:/etc/cube.toml
      - /data/matrixkv/node2:/data/matrixkv
    command: 
      - --addr=node2:8080
      - --cfg=/etc/cube.toml
      # shard will split after 16 bytes
      - --shard-capacity=16
    depends_on:
      - node1

  node3:
    image: matrixkv
    ports:
      - "8083:8080"
    volumes:
      - ./cfg/node3.toml:/etc/cube.toml
      - /data/matrixkv/node3:/data/matrixkv
    command: 
      - --addr=node3:8080
      - --cfg=/etc/cube.toml
      # shard will split after 16 bytes
      - --shard-capacity=16
    depends_on:
      - node0
      - node1
      - node2
